name: anitrack
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 0.0.3+4

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_web_auth_2: ^4.1.0
  flutter_secure_storage: ^10.0.0
  go_router: ^14.8.0
  http: ^1.3.0
  flutter_local_notifications: ^17.2.3
  riverpod: ^2.6.1
  shared_preferences: ^2.5.1
  skeletonizer: ^2.1.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/app_icon_flutter_dash.png
  adaptive_icon_background: "#041A2A"
  adaptive_icon_foreground: assets/images/app_icon_flutter_dash.png

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf

